### ISSUE TITLE
German translations

### ISSUE THREAD

**Issue by sys4-fr** [Xanthin/sys4_quests#1]
Hi Xanthin, I'm planning to rewrite quests once again. So wait a moment if you plan to add german translations again. But not worries about your last work, i plan to keep the same strings for existing quests and so your work (and mine) will not be lost. Once the quests will be rearranged/rewritten, i will leave a comment in the minetest forum. Great thanks for your work anyway.

**Comment by Xanthin** [comment]
No problem. :) Not a big thing. 
But thank YOU that you gave my request a try and made it so good!

**Comment by sys4-fr** [comment]
Hello :)
I have updated my master branch. So you can continue German translations once again ;)
I hope you will like my new system quest introduced with the group of quests of this last commit.
And thanks for your encouragements, it's very appreciable.
Bye !

**Comment by Xanthin** [comment]
> I hope you will like my new system quest introduced with the group of quests of this last commit.

I really like that, close to what I imagined and hoped for (as a former-CIV-player). :)
Again, excellent work.
